name: RecipeApp
options:
  bundleIdPrefix: com.gaston.recipeapp
  deploymentTarget:
    iOS: "17.0"
targets:
  RecipeApp:
    type: application
    platform: iOS
    sources:
      - path: RecipeApp
        excludes:
          - Info.plist
    info:
      path: RecipeApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gaston.recipeapp
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        GENERATE_INFOPLIST_FILE: "NO"
  RecipeAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - RecipeAppUITests
    dependencies:
      - target: RecipeApp
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
